### ISSUE TITLE
[1.20]A crash

### ISSUE THREAD

**Issue by windy664** [klikli-dev/modonomicon#130] opened 2023-07-04 08:46 UTC
**Describe the bug**

**To Reproduce**
I'm running on server , and i don't kown how it happen.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Modonomicon Version: latest
- Windows]
- Minecraft Version:latest
- Modpack Link and Version, or list of mods: in crash-report

**Additional context**

[crash-2023-07-04_16.38.50-server.txt](https://github.com/klikli-dev/modonomicon/files/11947017/crash-2023-07-04_16.38.50-server.txt)

**Comment by klikli-dev** [comment] 2023-07-08 09:21
@suiheng thank you for the report, I will look into it.
As this is a "server hang" type of situation it could be random bad luck - if a tick takes more than 60 seconds the server kills itself.
Could you maybe post your average server tps (or if the console sometimes logs "tick took too long" without crashing) and/or try to unlock any advancement (e.g. with command) and see if it hangs again?

**Comment by windy664** [comment] 2023-07-08 09:23
> 谢谢你的报告，我会调查的。由于这是“服务器挂起”类型的情况，因此可能是随机的坏运气 - 如果滴答时间超过60秒，服务器就会自行死亡。您能否发布您的平均服务器 tps（或者控制台有时记录“滴答声花了太长时间”而不会崩溃）和/或尝试解锁任何进步（例如使用命令）并查看它是否再次挂起？

tps alwasys 19

**Comment by klikli-dev** [comment] 2023-07-08 09:45
ok that's good!
I just did a quick check - I cannot reproduce the issue and there's nothing obviously wrong with the code (that part is unchanged for a while now).

Did this happen only once or does it happen repeatedly?

**Comment by windy664** [comment] 2023-07-08 11:37
> ok that's good! I just did a quick check - I cannot reproduce the issue and there's nothing obviously wrong with the code (that part is unchanged for a while now).
> 
> Did this happen only once or does it happen repeatedly?

happened only once so far

**Comment by klikli-dev** [comment] 2023-07-08 13:36
Ok thank you - I am inclined to think this might have been a random accident, so I will close this for now, but if it happens again please ping me and provide the updated log and we will reopen the investigation!

**Closed as completed by klikli-dev** 2023-07-08 13:36 UTC
Labels: bug
