### ISSUE TITLE
[1.20.4][NeoForge] Crash when trying to create a new world

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/modonomicon#178] opened 2024-02-29 04:15 UTC
**Describe the bug**
Crash when trying to create a new world

**To Reproduce**
1.Try to create a world with:SmartBrainLib-neoforge-1.20.4-1.13.jar, occultism-1.20.4-neoforge-1.116.2.jar, modonomicon-1.20.4-neoforge-1.60.0.jar 
2.Create a new world, and it will crash

**Expected behavior**
A create new world screen should appear

**System (please complete the following information):**
- Modonomicon Version: modonomicon-1.20.4-neoforge-1.60.0.jar 
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: 

**Additional context**
[crash-2024-02-28_23.06.26-client.txt](https://github.com/klikli-dev/modonomicon/files/14442714/crash-2024-02-28_23.06.26-client.txt)

**Comment by klikli-dev** [comment] 2024-02-29 08:08
This is a duplicate of https://github.com/klikli-dev/modonomicon/issues/177 which was fixed in the latest occultism version. If you update it should work :)

**Closed as completed by klikli-dev** 2024-02-29 08:08 UTC
Labels: bug
