### ISSUE TITLE
[1.19.2] Server crash - " Ticking entity " (Cannot read field X because X is null)

### ISSUE THREAD

**Issue by Gbergz** [klikli-dev/modonomicon#62] opened 2022-11-03 21:02 UTC
**Describe the bug**
Server crashes sometimes unexpectedly, not entirely sure why.

**To Reproduce**
So reproducing the bug seems to be hard, it doesn't happen all that often and I am not sure how to reproduce it.
Happens enough to be annoying.

**Expected behavior**
Expected server not to crash.

**Screenshots**
None.

**System (please complete the following information):**
- Modonomicon Version: 1.6.0
- OS: Linux (Server host)
- Minecraft Version: 1.19.2
- Forge Version: 43.1.47
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6/files/4061519
(Scroll down for a list of mods)
- Crash-Report: https://gist.github.com/Gbergz/8162794b8d11def662eee61381ca6731

**Additional context**
None.

**Comment by klikli-dev** [comment] 2022-11-04 07:49
@Gbergz I've had this reported before - it's a bit weird because the underlying issue is that the player's connection (which represents the actual connection from server to client) is not set. AFAIK that should never happen.

I will try to create a workaround, and also asked in Forge discord what may be going on here

**Comment by klikli-dev** [comment] 2022-11-04 08:04
@Gbergz Forge discord so far agreed with me that Modonomicon code should be fine. Can you provide more context?

When does it happen? When someone logs in? Is there anything else noticeably going on while this happens?

Please also provide your log files for around the time it crashes. 

Finally, you could try to remove any performance enhancement mods, in forge discord ItShallNotTick specifically was brought up as suspicious. If that fixes it we can talk to the mod author of that mod to see if we can get it fixed together

**Comment by klikli-dev** [comment] 2022-11-04 08:05
It seems this only happens in that specific modpack, see: https://github.com/klikli-dev/modonomicon/issues/47

It might be worth trying to look at https://www.modpackindex.com/modpacks/compare?modpacks=50949,47314 and see which (performance) mods are in TNP that are not in ATM that might cause this behaviour. 

Regardless, I will add a band-aid fix for you, but with the underlying issue present it is almost certain that you will run into other issues (with modonomicon or other mods), but the issues will not cause crashes, but rather simply something not working

**Comment by klikli-dev** [comment] 2022-11-04 08:25
Closed in #63 and #64 

@Gbergz 
1.7.1 should fix/work around the crash. Most likely it can be applied server-side only, clients should still be able to connect even without an update by TNP.

That said, as written above, it is recommended to have the underlying issue looked at - maybe get in touch with the pack authors to see if they have any info on it.

To summarize what forge discord said:
- The issue is likely a performance mod
- Possible suspects: `ItShallNotTick` and (just now) `canary`
- Trying to remove those two and see if it works with Modonomicon < 1.7.0 would confirm where the issue lies and allows you to contact the mod authors for a real fix

**Closed as completed by klikli-dev** 2022-11-04 08:25 UTC
Labels: bug

**Comment by Gbergz** [comment] 2022-11-04 09:46
Hey, thanks for trying to fix it. Late reply here bcs I was asleep.

Will try the stuff you mentioned and see if anything changes! Will first try the newest update.

I will update here with results.
