### ISSUE TITLE
mod fails to load correctly

### ISSUE THREAD

**Issue by Flame1211** [klikli-dev/modonomicon#144] opened 2023-07-21 04:48 UTC
**Describe the bug**
when launching the game I get "Error loading mods" Modonomicon has failed to load correctly

**To Reproduce**
1. launch game

**Expected behavior**
the game to launch correctly 

**Screenshots**
https://imgur.com/a/Hj0Ryva

**System (please complete the following information):**
- Modonomicon Version:  1.38.1
- OS: [e.g. Windows] windows 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
[modlist.txt](https://github.com/klikli-dev/modonomicon/files/12116353/modlist.txt)
**Additional context**
[latest.log](https://github.com/klikli-dev/modonomicon/files/12116361/latest.log)

**Comment by klikli-dev** [comment] 2023-07-21 05:04
Thanks for reporting - it's a bit odd because 1.38.1 should have fixed exactly that but it reproduces on my end! 

EDIT: It is really odd, the 1.38.1 compiled locally and dropped into a modpack works, the one from curseforge doesn't .. looks like something went wrong on upload

EDIT 2: This is extremely weird as even when making changes it continues to work for the locally produced file but never for the file automatically generated by github.

**Comment by klikli-dev** [comment] 2023-07-21 07:20
Until the build issue is resolved, @Flame1211, you can try https://curseforge.com/minecraft/mc-mods/modonomicon/files/4656145 which I manually uploaded and which works for me

**Comment by klikli-dev** [comment] 2023-07-21 09:03
Turns out this is an issue with the build process not with the mod.
For future reference, the "publish" gradle task somehow produces a jar that is not remapped, which replaces the previously created working remapped jar from the "build" gradle task.

Running publish at the bottom, after distributing the jars to the mod platforms works around this this

**Comment by klikli-dev** [comment] 2023-07-21 09:05
Closed in 6e7214a716854c93a8dd3d6c6608f0142d7c0022

**Closed as completed by klikli-dev** 2023-07-21 09:05 UTC
Labels: bug
